{{- $name := include "sh360-hotels.fullname" . -}}
{{- $sqlsrv := include "sql-name" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "sh360-hotels.name" . }}
    chart: {{ template "sh360-hotels.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  Hotels_ConnectionStrings__DefaultConnection: Server={{ $sqlsrv }};Initial Catalog=HotelsDb;Persist Security Info=False;User ID={{ .Values.mssql.user }};Password={{ .Values.mssql.pwd }};MultipleActiveResultSets=False;Connection Timeout=30;
  Hotels_b2c__Tenant: smarthotel360.onmicrosoft.com
  Hotels_b2c__ClientId: 9904b38a-126d-40d3-9ace-500ccad15839
  Hotels_b2c__Audiences: b3cfbe11-ac36-4dcb-af16-8656ee286dcc,9904b38a-126d-40d3-9ace-500ccad15839
  Hotels_b2c__Policy: B2C_1_SignUpInPolicy
  Hotels_discountsvc: http://discounts/
  Hotels_currency__Badge: $
  Hotels_currency__BaseConversion: "1.0"  
  ApplicationInsights__InstrumentationKey:  {{ .Values.appinsights.id }}
